# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PipelinePlaner
                                 A QGIS plugin
 Allows the user to create a line and evaluate impacts
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-11
        copyright            : (C) 2022 by André E.C.O.
        email                : andre.estevam97@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PipelinePlaner class from file PipelinePlaner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pipeline_planer import PipelinePlaner
    return PipelinePlaner(iface)
